### ISSUE TITLE
Updating to chromium m70

### ISSUE THREAD

**Issue by RyoKodama** [igel-oss/meta-browser-hwdecode#3]
Hi Damian-san

I'm trying to update the recipe for Chromium m70(which is the latest version).
I got an error in the file below. 
https://github.com/Igalia/chromium/commit/76fc3d9601c926972d225d1e9450dd7d19643fc4#diff-dfefd005e45dd1f32587ad31d2b513f7R28
The error indicates Thare's no media/gpu/features.h.
Is it needed to remain this line? 

And there is another error.
| In file included from gen/base/debug/debugging_buildflags.h:7:0,
|                  from ../../base/location.h:14,
|                  from ../../base/message_loop/watchable_io_message_pump_posix.h:8,
|                  from ../../base/message_loop/message_pump_libevent.h:13,
|                  from ../../base/message_loop/message_pump_for_io.h:22,
|                  from ../../base/message_loop/message_loop_current.h:11,
|                  from ../../base/message_loop/message_loop.h:17,
|                  from ../../base/threading/thread.h:16,
|                  from ../../media/gpu/v4l2/v4l2_video_decode_accelerator.h:24,
|                  from ../../media/gpu/v4l2/v4l2_video_decode_accelerator.cc:5:
| ../../build/buildflag.h:45:66: error: missing binary operator before token "("
|  #define BUILDFLAG(flag) (BUILDFLAG_CAT(BUILDFLAG_INTERNAL_, flag)())
|                                                                   ^
| ../../media/gpu/v4l2/v4l2_video_decode_accelerator.cc:71:6: note: in expansion of macro 'BUILDFLAG'
|  #if !BUILDFLAG(USE_LINUX_V4L2)
|       ^~~~~~~~~
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc4/build_m3/tmp/work/aarch64-agl-linux/chromium-ozone-wayland/70.0.3509.0.r579363.igalia.1-r0/temp/log.do_compile.6606)
ER

This is also same file as first error. 
https://github.com/Igalia/chromium/commit/76fc3d9601c926972d225d1e9450dd7d19643fc4#diff-dfefd005e45dd1f32587ad31d2b513f7R71
I don't think definition of BUILDFLAG is not bad. this has not been changed long time.
Could you check if you are available?

**Comment by dhobsong** [comment]
Kodama-san,

I believe that both errors are related to the same problem.  Line 28 of that file should be 
```
#include "media/gpu/buildflags.h"
```
instead of `features.h`

`buildflags.h` is the newer version of `features.h` and is autogenerated, so maybe there was some transition period where both filenames were created during the build.  I will try it locally here too, but
please let me know if the above fixes the problem for you.

**Comment by dhobsong** [comment]
Kodama-san,

I've verified that changing the above line to buildflags.h is working with the latest version of the igalia/chromium repository, and that the chromium patches from this repository are not needed any more.  So I will remove the those patches and close this issue.

Thank you,
Damian

**Comment by msisov** [comment]
Also, we made the recipe to use v4l2 related gn args by default - 
https://github.com/Igalia/meta-browser/blob/ozone/wayland/71.0.3545.0.r589108/recipes-browser/chromium/chromium-ozone-wayland_71.0.3545.0.r589108.igalia.1.bb#L39

so, you only need to build v4l-gst, libv4l and libv4l-dev with the patches from here .

**Comment by dhobsong** [comment]
Oh great.  So it looks like I can get rid of the whole bbappend. That makes it nice and clean.

**Comment by RyoKodama** [comment]
Damian-san

Thank you for considering and I'm sorry I didn't reply so I didn't have a time to do this issue.

Maksim
Thank you for letting us know
